# Generated by Django 2.2.1 on 2019-09-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='news',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='score',
            field=models.FloatField(default=None, max_length=10),
        ),
    ]
