# Generated by Django 2.2.1 on 2019-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20190928_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='news',
        ),
        migrations.AddField(
            model_name='company',
            name='graph_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='words_frequency_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/'),
        ),
    ]
